== Changes

=== 0.3.2

* Replace single-segment namespace with Potemkin's `import-vars` to fix out-of-sync conversion graphs
* Upgrade to Manifold 0.3.0, remove unused dev deps
* Update docstring on `to-string` not being lazy
* Add basic clj-kondo support
* Fixed nonstandard indentation
* Deprecated single-segment namespace in README examples

Contributions by Eugen Stan, Eugene Pakhomov, and Matthew Davidson

=== 0.3.1

* Ensured close-on-exhaustion behavior when doing whole java.io.File-based conversion
* Removed problematic finalizer that could prematurely close a large file before conversion was finished
* Fixed broken transfer append behavior on Mac/Windows
* Simplified some conversion pathways

Contributions by Matthew Davidson

=== 0.3.0

* Copied code and tests to nested namespaces, deprecated top-level single-segment ns for Graal/clj-easy
* Bumped Manifold dep to 0.2.3

Contributions by skynet

=== 0.2.10

* Removed use of clj-tuple

Contributions by Matthew Davidson

=== 0.2.9

* Removed use of fast-memoize

Contributions by Joshua Degagné

=== 0.2.6 - 0.2.8

* Update group ID
* Internal deployment changes

Contributions by Erik Assum

=== 0.2.5

* Add CircleCI support, remove Travis
* Add basic clj-kondo linting hints
* Bring under clj-commons
* Minor docstring changes for clarity
* Fix Markdown code block language string
* Bumped up some deps. In particular, Manifold dep upgraded to 0.1.9
* Fix incorrect tag metadata emission
* Update some variable names for clarity
* Fix reflection warnings
* Fix for compare-bytes bug

Contributions by Erik Assum, Matthew Davidson, Andy Fingerhut, Akshay Gollapalli, Dominic Pearson, Zach Tellman, and vemv.

=== < 0.2.5-alpha2

See git history.
